# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:

  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"
  - trigger: ":ods"
    replace: "muchas gracias por tu contacto. Por el momento no estoy interesado en un cambio profesional, pero me gustaría q sigamos en contacto para futuras búsquedas"
  - trigger: ":ode"
    replace: "I'm very thankful you consider being part of this project. Right now, I'm not looking for a professional change, but I will be very happy to keep in touch for future opportunities."
  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/